# Generated by Django 3.1.6 on 2021-02-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210215_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
