# Generated by Django 3.1.6 on 2021-02-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210215_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='update_date',
        ),
    ]
