# Generated by Django 3.1.6 on 2021-02-16 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.difficulty'),
        ),
    ]
