# Generated by Django 3.1.5 on 2021-01-28 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='很懒的一个用户', max_length=128)),
                ('phone', models.CharField(default='12138', max_length=11)),
                ('address', models.CharField(default='用户很懒，没填写地址', max_length=256)),
                ('abstract', models.TextField(default='用户很懒，没有描述')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
